### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-5#40]
*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Code is abstracted to functions with good function design

-  [ ] Functions do not follow a consistent style. **- 1**

-  [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 3**

All of the functions.

-  [ ] There is not at least 1 function per group member. **- 3**

### Functions are well documented

- [ ] Documentation does not follow a consistent style. **- 1**

Compare `boxplot_plotting` to the rest

### Helper data for tests is tractable and reproducible

- [ ] The data used could be a simple hand made data instead of the the original dataset.  **- 1**

`mean_cross_val_scores`

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 2 expected input. **- 1**

`boxplot_plotting`, `plot_hist_overlay`

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 3**

All of the functions.
- [ ] There are cases of functions that do not test at least 1 wrong input. **- 3**

All of the functions.

- [ ] There is not at least 1 function being tested per group member. **- 3**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ]  I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**
