### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-5#57]
## Rubric
- 18 / 25: Analysis code is abstracted to four (or more) scripts which take command line arugments and save analysis artifacts (e.g., figures and data for tables).
- 23 / 25: Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.
- 23 / 25: A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis
- 2 / 2: Dependencies have been updated (so it include the test libraries)
- 2 / 2: Project file and directory structure organization
- 2 / 2: GitHub Project board
- 2 / 2: GitHub Issue Milestones
- 2 / 2: Follows GitHub flow version control workflow
- 2 / 2: GitHub release
- 11 / 13: Analysis can be run reproducibly using documentation provided in the README.

## Commonly provided feedback

Recommended to open an issue in the project's repository to provide this feedback so students can act on it.
In milestone 4, these things will be regraded as part of the final grade for the project.
Bolded points indicate how many points should be taken off the rubric for each of these.
These numbers do not need to be included in the GitHub issue.

Text to copy and paste into GitHub issue before providing specific comments:

*Congratulations on finishing milestone 2! We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Analysis code is abstracted to four (or more) scripts which take command line arguments and save analysis artifacts (e.g., figures and data for tables).

- [ ] One or more scripts are not well documented **- 4**

All of the scripts are missing documentation.

- [ ] One or more scripts are not well organized **- 3**

`src/load_data.py` and `src/clean_data.py` define functions that could be defined in another python file and loaded by the scripts.

function `build_test_model` from `src/build_test_model.py` could be broken into smaller functions and even save them in another python file.

### Report is written in a literate code document, and the code in the literate code document primarily functions to source analysis artifacts and format the document.

- [ ] The literate code document (R Markdown or Jupyter notebook) uses markup language syntax to reference tables and figures so that the correct table and figure numbers are automatically used but does so inconsistently  **- 2**

Sometimes you reference figures like "boxplots above" which is not so clear and sometimes you use "Figures 1.7"

### A data analysis pipeline written in GNU Make exists, and works to run the analysis from beginning to end, as well as to clean up the analysis

- [ ] Target `all` could be simplified by writing something like `all: <report_target>`. **- 2**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] Usage documentation could be improved for clarity (i.e., it is not explicitly clear to the user how to use the project, or some of the wording is confusing). **-2**

Technically, you should `cd work/DSCI-310-Group-5` inside of the container or leave instruction to `cd` the repository before opening the container
