### ISSUE TITLE
Milestone 4 feedback

### ISSUE THREAD

**Issue by GiuseppeTT** [DSCI-310/DSCI-310-Group-5#58]
*Congratulations on finishing your final project!!! This is a great accomplishment and you should be proud!
Below we list some specific feedback you can use to improve your project if you so desire,
but most importantly to learn.
We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.*

### Addressed feedback given by the teaching team from milestone 2

- [ ] Feedback issue on GitHub was not used by the group. **- 12.5**

- [ ] 20% of the feedback given by the teaching team from milestone 2 was not addressed **-5**

There are feedback points that were not addressed. For instance, the README contains incorrect instructions. You can check section "Analysis can be run reproducibly using documentation provided in the README" for more details.

### The software package is well documented

- [ ] It is missing vignette/tutorials docs. **- 1**

### Continuous integration is used to automate the running of software tests for the package functions

- [ ] There was no attempt. **- 5**

### Dependencies have been updated (so it include the newly created external software package)

- [ ] Dependencies have been updated but do not work in the final image. **- 0.5**

### Project file and directory structure organization

- [ ] There are folder/files that should not be committed. **- 0.5**

`.virtual_documents/notebooks/`

### GitHub release

- [ ] Your link on canvas says v0.0.4, but the url links to v0.0.2. **- 0.5**

I graded the work based on version v0.0.2

###  Analysis can be run reproducibly using documentation provided in the README

- [ ] I got an error while following the instructions

I based my grading on version `latest`. **- 2.5**

```
[giuseppett@fedora test]$ docker pull nhantien/dsci310group5:v0.7.0

Error response from daemon: manifest for nhantien/dsci310group5:v0.7.0 not found: manifest unknown: manifest unknown
```

- [ ] I got an error while trying to run `make all`. **- 2.5**

You are missing your group package

```
(base) jovyan@fafc54126be6:~/work$ make all
python3 src/load_data.py data/raw/breast_cancer.txt data/raw/breast_cancer.csv
python3 src/clean_data.py data/raw/breast_cancer.csv data/processed/train_df.csv data/processed/test_df.csv
python3 src/EDA_plots.py data/processed/train_df.csv results/figures/hist_plot.png results/figures/boxplot_plot.png
Traceback (most recent call last):
  File "/home/jovyan/work/src/EDA_plots.py", line 6, in <module>
    from dsci_prediction.dsci_prediction import *
ModuleNotFoundError: No module named 'dsci_prediction.dsci_prediction'
make: *** [Makefile:25: results/figures/hist_plot.png] Error 1
```
