### ISSUE TITLE
Milestone 2 feedback addressed

### ISSUE THREAD

**Issue by edile47** [DSCI-310/DSCI-310-Group-5#59]
This is group 5 milestone 2 feedback response. 

### Code is abstracted to functions with good function design

-  [ ] Functions do not follow a consistent style. **- 1**

https://github.com/DSCI-310/DSCI_310_Group_5_Package/blob/main/src/DSCI_prediction/DSCI_prediction.py

The link above contains the four functions packaged in a py file. We have adjusted the functions so that they follow a consistent style. 

-  [ ] There are cases of functions that do not check for proper input and/or do not provide useful error messages. **- 3**

All of the functions.

https://github.com/DSCI-310/DSCI_310_Group_5_Package/blob/main/src/DSCI_prediction/DSCI_prediction.py

Same link as above. The function each checks for proper input and provide useful error messages.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/79818110/166678483-1628269b-6ee3-41f0-be37-6b380c492484.png">
<img width="398" alt="image" src="https://user-images.githubusercontent.com/79818110/166678564-15190d71-8d81-41dd-9db6-326e3b5389b4.png">
<img width="484" alt="image" src="https://user-images.githubusercontent.com/79818110/166678612-4ea73181-0cd9-4029-a8d7-f95cfa107127.png">

https://github.com/DSCI-310/DSCI_310_Group_5_Package/tree/main/tests

The link above contains test files for each function in the package repo. The functions test for incorrect input types. 
<img width="578" alt="image" src="https://user-images.githubusercontent.com/79818110/166678992-69b437f0-e2b9-45da-969d-0276d518f5aa.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/79818110/166679067-ecfc046c-0144-4749-a330-62ba85fd1c94.png">
<img width="440" alt="image" src="https://user-images.githubusercontent.com/79818110/166679131-e711e406-efbd-4aea-8048-515ee2357b22.png">
<img width="329" alt="image" src="https://user-images.githubusercontent.com/79818110/166679190-e9601feb-8e7c-42d8-8541-6b1169bcfb9f.png">

-  [ ] There is not at least 1 function per group member. **- 3**
We added more functions for milestone 4 so  we have plot_boxplot, plot_confusion_matrix, plot_hist, tuned_para_table (4 functions). 

### Functions are well documented

- [ ] Documentation does not follow a consistent style. **- 1**

Compare `boxplot_plotting` to the rest
https://github.com/DSCI-310/DSCI_310_Group_5_Package/blob/main/src/DSCI_prediction/DSCI_prediction.py
The link above contains the four functions packaged in a py file. We have adjusted the functions so that they follow boxplot_plotting function documentation style. 

### Helper data for tests is tractable and reproducible

- [ ] The data used could be a simple hand made data instead of the the original dataset.  **- 1**

`mean_cross_val_scores`
https://github.com/DSCI-310/DSCI_310_Group_5_Package/tree/main/tests
Above function is omitted. Now all 4 functions use original dataset. 

### Tests suite is of high quality

- [ ] There are cases of functions that do not test at least 2 expected input. **- 1**

`boxplot_plotting`, `plot_hist_overlay`

- [ ] There are cases of functions that do not test at least 1 edge-case input. **- 3**

All of the functions.

https://github.com/DSCI-310/DSCI_310_Group_5_Package/tree/main/tests
All four functions now test edge-case. 
test_plot_boxplot.py:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/79818110/166680459-a461faf8-ceff-4bec-b971-59fe7083a3a3.png">
test_plot_confusion_matrix.py :
<img width="445" alt="image" src="https://user-images.githubusercontent.com/79818110/166680578-328f1ef2-42a2-4111-9e31-b1bb9c049941.png">
test_plot_hist.py:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/79818110/166680663-8a957e5c-48eb-434c-a2e6-274931a2f4ee.png">
test_tuned_para_table.py:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/79818110/166680753-d9b2a583-9910-44b9-9692-aaea09021a3f.png">

- [ ] There are cases of functions that do not test at least 1 wrong input. **- 3**

All of the functions.

All four functions test at least 1 wrong input. 
https://github.com/DSCI-310/DSCI_310_Group_5_Package/tree/main/tests
test_plot_boxplot.py:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/79818110/166680989-4d26dddd-ff3f-46c6-a15f-da65f5484e85.png">
test_plot_confusion_matrix.py:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/79818110/166681097-e1c6614d-61b1-4530-9057-0ce1ec86ce0b.png">
test_plot_hist.py:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/79818110/166681160-d978efc6-1dec-41cc-8ec8-8d56d043b5f9.png">
test_tuned_para_table.py:
<img width="359" alt="image" src="https://user-images.githubusercontent.com/79818110/166681232-47b16544-b838-482e-9673-7225642122fe.png">

- [ ] There is not at least 1 function being tested per group member. **- 3**

###  Analysis can be run reproducibly using documentation provided in the README

- [ ]  I could not reproduce the analysis because there is no repository available inside the container. The docker command is probably missing a volume argument. **- 3**
